import React from 'react'

export const About = () => (
  <div>
    <h2>About Page</h2>
    <p>This is mostly about us.</p>
    <p>LABS WAS INITIALLY A CREATIVESHOP FOUNDED BY THE STUDENTS OF ACADEMY OF RBK, ARCHITECTURE, AND DESIGN IN JORDEN</p>
  <p>AND COLLABORATED WITH INTERNATIONAL COMMUNICATION AGENCIES ON MARKETING AND COMMUNICATION CAMPAIGNS FOR THEIR CLIENTS.</p>

  </div>
) 

